### ISSUE TITLE
Field '_offsetAnimation' has not been initialized.

### ISSUE THREAD

**Issue by redDwarf03** [koukibadr/Elegant-Notification#116]
Hello, 

i have an error sometimes when many notifications should be displayed but sorry, i don't find exactly the use case to reproduce it...
Here is the version i used and the associated error

Version: 
```
  elegant_notification:
    git:
      url: https://github.com/koukibadr/Elegant-Notification.git
      ref: dev
```

Error:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following LateError was thrown building ElegantNotification(state:
ElegantNotificationState#83b8e(ticker inactive)):
LateInitializationError: Field '_offsetAnimation' has not been initialized.

The relevant error-causing widget was:
  ElegantNotification
  
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
packages/elegant_notification/elegant_notification.dart 393:26                    get [_offsetAnimation]
packages/elegant_notification/elegant_notification.dart 628:24                    build
```
